# Generated by Django 4.2.7 on 2023-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('autor', models.TextField()),
                ('descricao', models.TextField()),
                ('preco', models.TextField()),
                ('qtdDisponivel', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
