# Generated by Django 4.2.7 on 2023-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtdDisponivel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(max_length=120),
        ),
    ]
