# Generated by Django 4.2.7 on 2023-11-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
